### ISSUE TITLE
How to correct get list of objects for RPC operations?

### ISSUE THREAD

**Issue by NikolayKolyada** [OpenNetworkingFoundation/TAPI#156]
Hello!

In the last version of TAPI we found next:
All PRC operations for get list of some objects, for example "/operations/getConnectivityServiceList/", contains List with concrete object. Swagger example:

```
  GetConnectivityServiceListRPCOutputSchema:
    properties:
      connService:
        items:
          $ref: '#/definitions/ConnectivityService'
        type: array
        description: none
```

And this behavior valid for all swagger files and all requests for lists of objects(GetServiceEndPointListRPCOutputSchema, GetConnectionListRPCOutputSchema, GetConnectivityServiceListRPCOutputSchema and etc.).

BUT only for : "/operations/getTopologyList/" previous behavior is broken. 
 "/operations/getTopologyList/" return list of UUID's. 
Example: 

```
  GetTopologyListRPCOutputSchema:
    properties:
      topology:
        items:
          type: string
          x-path: '/Context/_topology/{uuid}/'
        type: array
        description: none
```

What is the right behaviour of the items listed above?

Thanks!
